### ISSUE TITLE
Error: too many tokens

### ISSUE THREAD

**Issue by DartPower** [SciSharp/LLamaSharp#171]
Hi, im very novice in C#. And how to solve this problem? 

Code:

```
using LLama;
using LLama.Common;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;

namespace Camella
{
    public class Program
    {
        [STAThread]
        public static void Main()
        {
            Marshal.PrelinkAll(typeof(Program));
            Trace.AutoFlush = true;
            Trace.Listeners.Clear();
            Trace.Listeners.Add(new ConsoleTraceListener());
            Trace.Listeners.Add(new TextWriterTraceListener(System.IO.Path.GetFileNameWithoutExtension(typeof(Program).Assembly.GetName().Name) + ".log"));
            Process currentProcess = Process.GetCurrentProcess();
            currentProcess.PriorityClass = ProcessPriorityClass.High;
            Console.BackgroundColor = ConsoleColor.Black;
            Console.ForegroundColor = ConsoleColor.White;
            try
            {
                Trace.Write("Please input your model path: ");
                var modelPath = Console.ReadLine();

                Trace.Write("Please input your prompt: ");
                var prompt = Console.ReadLine();

                var parameters = new ModelParams(modelPath)
                {
                    ContextSize = 1024,
                    Seed = 1337,
                    GpuLayerCount = 5
                };
                using var model = LLamaWeights.LoadFromFile(parameters);
                using var context = model.CreateContext(parameters);
                var executor = new InteractiveExecutor(context);

                var session = new ChatSession(executor);

                Console.ForegroundColor = ConsoleColor.Yellow;
                Trace.WriteLine("The chat session has started. In this example, the prompt is printed for better visual result.");
                Console.ForegroundColor = ConsoleColor.White;

                // show the prompt
                Trace.Write("You: " + prompt);
                while (prompt != "stop")
                {
                    foreach (var text in session.Chat(prompt, new InferenceParams() { Temperature = 0.6f, AntiPrompts = new List<string> { "User:" } }))
                    {
                        Trace.Write(text);
                    }
                    
                    Console.ForegroundColor = ConsoleColor.Green;
                    prompt = Console.ReadLine();
                    Console.ForegroundColor = ConsoleColor.White;
                }

                session.SaveSession("SavedSessionPath");
            }
            catch (Exception value)
            {
                try
                {
                    Trace.WriteLine(DateTime.Now);
                    Trace.WriteLine(value.ToString());
                    Trace.WriteLine("");
                }
                catch
                {
                }
            }
        }
    }
}
```

Result:
```
Please input your model path: \\SRV\ai\_Models\llama-2-7b-guanaco-qlora.Q2_K.gguf
Please input your prompt: Hi, 4el.
llama_model_loader: loaded meta data with 19 key-value pairs and 291 tensors from \\SRV\ai\_Models\llama-2-7b-guanaco-qlora.Q2_K.gguf (version GGUF V2 (latest))
/* Here too many (maybe) unuseful model info */
llm_load_tensors: ggml ctx size =    0.09 MB
llm_load_tensors: mem required  = 2694.41 MB (+  512.00 MB per state)
.................................................................................................
llama_new_context_with_model: kv self size  =  512.00 MB
llama_new_context_with_model: compute buffer total size =   89.41 MB
The chat session has started. In this example, the prompt is printed for better visual result.

Hi, 4el. kwietn. 2019 r.

Z dnia 4 kwietnia 2019 r. wlaczona do Katalogu Archiwow Panstwowych.
 User:
llama_tokenize_with_model: too many tokens
13.09.2023 15:48:14
LLama.Exceptions.RuntimeError: Error happened during tokenization. It's possibly caused by wrong encoding. Please try to specify the encoding.
   at LLama.Native.SafeLLamaContextHandle.Tokenize(String text, Boolean add_bos, Encoding encoding)
   at LLama.LLamaContext.Tokenize(String text, Boolean addBos)
   at LLama.InteractiveExecutor.PreprocessInputs(String text, InferStateArgs args)
   at LLama.StatefulExecutorBase.Infer(String text, IInferenceParams inferenceParams, CancellationToken cancellationToken)+MoveNext()
   at LLama.ChatSession.Chat(String prompt, IInferenceParams inferenceParams, CancellationToken cancellationToken)+MoveNext()
   at Camella.Program.Main() in Q:\!DartPower_Projects\_CSharp_Projects\Camella\Camella\Program.cs:line 52
```

Using version 0.5.1 published for NuGet

P.S. Prompt has "Hi, 4el." and another any one too can trigger this error

**Comment by AsakusaRinne** [comment]
Hi, which model were you using? The prompt seems to be non-English, usually this problem may be caused by the two reasons:
1. The model does not support your language well.
2. The encoding-decoding of your language does not work well, which indicates a BUG of LLamaSharp.

**Comment by DartPower** [comment]
Model is:
llama-2-7b-guanaco-qlora.Q2_K.gguf

Promt:
"Can you write C# code console game Cat Simulator? Like The Sims but The Cats."

And 
```The encoding-decoding of your language does not work well, which indicates a BUG of LLamaSharp.```
**Thanks for hint.** ! 😃 
``` <NeutralLanguage>en-US</NeutralLanguage> ```
**Added this to csproj, and...** 
![image](https://github.com/SciSharp/LLamaSharp/assets/2005369/fa671501-5de3-4c71-8e12-0740c143eb96)
it's works
