### ISSUE TITLE
Failed to load model

### ISSUE THREAD

**Issue by sksdev27** [SciSharp/LLamaSharp#187]
Has anyone ran in to the following problem when loading Llama models.
I tried the following models all result in same error:
Models are:
1. ggml-model-q4_0.bin
2. ggml-vic13b-uncensored-q8_0.bin.crdownload
3. llama-2-7b-guanaco-qlora.ggmlv3.q2_K.bin
4. wizardLM-7B.ggmlv3.q4_0.bin

LlamaSharp faild to load the model. Exit on the following code:
Console.Write("Please input your model path: ");
var modelPath = "E:\\wizardLM-7B.ggmlv3.q4_0.bin";
Console.Write($"{modelPath}.");
var prompt = File.ReadAllText("Assets/chat-with-bob.txt").Trim();

var parameters = new ModelParams(modelPath)
{
    ContextSize = 1024,
    Seed = 1337,
    GpuLayerCount = 5
};
using var model = LLamaWeights.LoadFromFile(parameters);

with the following Error stack when i use the Example Code (https://github.com/SciSharp/LLamaSharp/tree/master/LLama.Examples) :
```
   at LLama.Native.SafeLlamaModelHandle.LoadFromFile(String modelPath, LLamaContextParams lparams) in E:\LLamaSharp-master\LLamaSharp-master\LLama\Native\SafeLlamaModelHandle.cs:line 61
   at LLama.LLamaWeights.LoadFromFile(IModelParams params) in E:\LLamaSharp-master\LLamaSharp-master\LLama\LLamaWeights.cs:line 57
   at LLama.Examples.NewVersion.ChatSessionStripRoleName.<Run>d__0.MoveNext() in E:\LLamaSharp-master\LLamaSharp-master\LLama.Examples\NewVersion\ChatSessionStripRoleName.cs:line 20
   at LLama.Examples.NewVersion.NewVersionTestRunner.<Run>d__0.MoveNext() in E:\LLamaSharp-master\LLamaSharp-master\LLama.Examples\NewVersion\TestRunner.cs:line 37
   at Program.<<Main>$>d__0.MoveNext() in E:\LLamaSharp-master\LLamaSharp-master\LLama.Examples\Program.cs:line 13
   at Program.<Main>(String[] args)
```

**Comment by bancroftway** [comment]
what version of llamasharp are you on?

**Comment by sksdev27** [comment]
So, version that works 0.4.1 but only the terminal since it doesn't have web functionality. When i switch over 0.4.2 and  0.5.1. Terminal version gives the same error on terminal and Web. I tried moving the web/web_api folder from 0.4.2 to 0.4.1.  I get the following error when I load the model and press create chat session:
llama_load_model_from_file: failed to load model
fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'LoadModel'.
      LLama.Exceptions.RuntimeError: Failed to load model E:\wizardLM-7B.ggmlv3.q4_0.bin.
         at LLama.Native.SafeLlamaModelHandle.LoadFromFile(String modelPath, LLamaContextParams lparams) in E:\LLamaSharp-0.4.2-preview\LLamaSharp-0.4.2-preview\LLama\Native\SafeLlamaModelHandle.cs:line 55
         at LLama.Utils.InitLLamaContextFromModelParams(ModelParams params) in E:\LLamaSharp-0.4.2-preview\LLamaSharp-0.4.2-preview\LLama\Utils.cs:line 46
         at LLama.LLamaModel..ctor(ModelParams Params, String encoding, ILLamaLogger logger) in E:\LLamaSharp-0.4.2-preview\LLamaSharp-0.4.2-preview\LLama\LLamaModel.cs:line 56
         at LLama.Web.Services.ConnectionSessionService.CreateAsync(LLamaExecutorType executorType, String connectionId, String modelName, String promptName, String parameterName) in E:\LLamaSharp-0.4.2-preview\LLamaSharp-0.4.2-preview\LLama.Web\Services\ConnectionSessionService.cs:line 54
         at LLama.Web.Hubs.SessionConnectionHub.OnLoadModel(LLamaExecutorType executorType, String modelName, String promptName, String parameterName) in E:\LLamaSharp-0.4.2-preview\LLamaSharp-0.4.2-preview\LLama.Web\Hubs\SessionConnectionHub.cs:line 49
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)

**Comment by saddam213** [comment]
Looks like your trying to Load a GGML model, LLamaSharp only supports GGUF

**Comment by sksdev27** [comment]
@saddam213 Thank you GGUF model worked. but now its just replying gibberish:
`User: Hello, Bob.
Bob: Hello. How may I help you today?
User: Please tell me the largest city in Europe.
Bob: Sure. The largest city in Europe is Moscow, the capital of Russia.
User:what is an apple?
 millies Ol collectedederIteratorusepackageights django Géographieplugin Normdaten nav actually linux Gabriel accomplThatánicoOctelijk ???? cual ?????? '" kall?Instance require miserPLOoupe grasp drums limitstons∩ monument nä powers sen force? ???SequenceAPointsiera safe Border [-ificateership answered survey Upper valeisat worseózventory export Western."édie Ceccertainnoteslav illustr illustr? dict`
