### ISSUE TITLE
Semantic Kernel Runtime Error

### ISSUE THREAD

**Issue by nathanfolkman** [SciSharp/LLamaSharp#195]
```
Unhandled exception. System.TypeLoadException: Method 'GetChatCompletionsAsync' in type 'LLamaSharp.SemanticKernel.ChatCompletion.LLamaSharpChatCompletion' from assembly 'LLamaSharp.SemanticKernel, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at LLama.Examples.NewVersion.Program.Main(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at LLama.Examples.NewVersion.Program.Main(String[] args)
   at LLama.Examples.NewVersion.Program.<Main>(String[] args)
```

**Comment by xbotter** [comment]
It seems to be an issue caused by the semantic kernel version upgrade. I can take a look at it.

**Comment by nathanfolkman** [comment]
Appreciated, please let me know if there is any additional information I can provide that would help.

**Comment by SignalRT** [comment]
@nathanfolkman I tried to run LLamaExamples (11, 12 and 13) and I don´t get that error in the current master.

**Comment by xbotter** [comment]
@nathanfolkman If you are running examples, please update to the latest code and try again.

**Comment by nathanfolkman** [comment]
Works great, thanks so much for looking into this!
