### ISSUE TITLE
LLama.Exceptions.RuntimeError: Failed to load model

### ISSUE THREAD

**Issue by TonyWang666** [SciSharp/LLamaSharp#332]
Hi Team. I fail to load the model for `llam-2-70b-chat` on my mac. Any hint will be appreciated.
Below are my model and PC information:
**PC**: Mac M2
**Nuget Package**: LLamaSharp 0.8.0; LLamaSharp.Backend.Cpu 0.8.0
**Model**: llama-2-70b-chat (download from official repo)

Below are the error stacktrace:
LLama.Exceptions.RuntimeError: Failed to load model /Users/twang/git/models/llama/llama-2-70b-chat/.
   at LLama.Native.SafeLlamaModelHandle.LoadFromFile(String modelPath, LLamaModelParams lparams)
   at LLama.LLamaWeights.LoadFromFile(IModelParams params)
   at Program.<>c.<<Main>$>b__0_5(IServiceProvider sp) in /Users/twang/git/modmate/mod-mate/mod-mate/Program.cs:line 87
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method9(Closure, IServiceProvider, Object[])
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by SignalRT** [comment]
The models supported are models with GGUF format. Please review the documentation:

![image](https://github.com/SciSharp/LLamaSharp/assets/16475613/a08c62b2-342e-4e27-adbe-b656050a5584)

It seems that you are trying to load directly the model downloaded from meta repositories https://github.com/facebookresearch/llama that don´t use GGUF format. If this is the case you need to convert previously the model to GGUF format or download a GGUF model (for example in this repository https://huggingface.co/TheBloke you will find a lot of models converted to GGUF).

If the library fails to load a GGUF model, please indicate the link to download the model to be able to verify the issue. You also should have in consideration that you will need a lot of memory to load a 70b parameter model.

**Comment by TonyWang666** [comment]
Hi [jlsantiago](https://github.com/SignalRT), thank you very much. I plan to use gguf file from https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/blob/main/llama-2-7b-chat.Q5_K_M.gguf. Will update the result later in this thread.

**Comment by TonyWang666** [comment]
> @TonyWang666, Did you have time to test some gguf model with LLamaSharp ?

Yeah, I can do the test today. Sorry for the delay.
