### ISSUE TITLE
qwen support

### ISSUE THREAD

**Issue by mayuanyang** [SciSharp/LLamaSharp#425]
I am running Qwen model, it throw exception on token 27820 as screenshot below

![image](https://github.com/SciSharp/LLamaSharp/assets/3387099/8117ba7d-185d-43ec-94ee-46956e4cdc7b)
The span it return is actually 20, and exception details here
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at LLama.StreamingTokenDecoder.<Add>g__TokenToBytes|9_0(Byte[]& bytes, Int32 token, SafeLlamaModelHandle model)
   at LLama.StreamingTokenDecoder.Add(Int32 token)
   at LLama.StreamingTokenDecoder.AddRange(IEnumerable`1 tokens)
   at LLama.StatefulExecutorBase.InferAsync(String text, IInferenceParams inferenceParams, CancellationToken cancellationToken)+MoveNext()
   at LLama.StatefulExecutorBase.InferAsync(String text, IInferenceParams inferenceParams, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Program.RunInstruct() in /Users/eddyma/Github/Hi200Gpt/Hi200Gpt/Hi200Gpt.Console/Program.cs:line 44
   at Program.RunInstruct() in /Users/eddyma/Github/Hi200Gpt/Hi200Gpt/Hi200Gpt.Console/Program.cs:line 44
   at Program.Main(String[] args) in /Users/eddyma/Github/Hi200Gpt/Hi200Gpt/Hi200Gpt.Console/Program.cs:line 9
   at Program.<Main>(String[] args)
```

Potential problem area
The codes
https://github.com/SciSharp/LLamaSharp/blob/402a110a3a7cc3424b6abf9a5214ffd545d30878/LLama/Native/NativeApi.cs#L478

Any thought?

**Comment by martindevans** [comment]
Ah yes there's definitely a bug there.

```csharp
// Try to get bytes
var l = model.TokenToSpan(token, bytes);
```

This code will get the length of the token and **nothing** will be written to the buffer if the length > buffer.

```csharp
// Negative length indicates that the output was too small. Expand it to twice that size and try again.
if (l < 0)
{
```

However this code assumes that the length will be negative if it was too big!

I've just opened #428 which hopefully should fix this, could you test it out and confirm if it works for you before I merge it? Thanks.

**Comment by mayuanyang** [comment]
any schedule to release the new nuget for this patch?

**Comment by martindevans** [comment]
No _schedule_ exactly, but we'll probably look at a small bugfix release soon (end of this week maybe).
