### ISSUE TITLE
NativeApi: `TryLoadLibrary()` can fail for some systems

### ISSUE THREAD

**Issue by swharden** [SciSharp/LLamaSharp#524]
My system does not have a cuda-supported graphics card, but LLamaSharp's native API class detects cuda version 12.

![image](https://github.com/SciSharp/LLamaSharp/assets/4165489/00e19621-f759-4139-8dad-2d69b37ca694)

The result is that the first time I try to interact with a LLM, I get an exception:
```
ggml_backend_cuda_init: error: invalid device 0
llama_new_context_with_model: failed to initialize CUDA0 backend
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at LLama.Native.NativeApi.llama_n_ctx(LLama.Native.SafeLLamaContextHandle)
--------------------------------
   at LLama.Native.SafeLLamaContextHandle.get_ContextSize()
   at LLama.LLamaContext.get_ContextSize()
   at LLama.StatefulExecutorBase..ctor(LLama.LLamaContext, Microsoft.Extensions.Logging.ILogger)
   at LLama.InteractiveExecutor..ctor(LLama.LLamaContext, Microsoft.Extensions.Logging.ILogger)
   at LLama.Examples.Examples.ChatSessionWithHistory+<Run>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at LLama.Examples.Examples.ChatSessionWithHistory.Run()
   at LLama.Examples.Examples.Runner+<Run>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at LLama.Examples.Examples.Runner.Run()
   at Program+<<Main>$>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Program.<Main>$(System.String[])
   at Program.<Main>(System.String[])
```

## Details

Note that this file is present in my build folder (which is why cuda 12 is "detected"), but the only graphics card on my system is a GeForce GT 710 which I don't think supports cuda 11 or 12

```
./runtimes/win-x64/native/cuda12/llama.dll
```

This is the code that runs "successfully", deciding that I should be running cuda 12 because it found the DLL and loaded it
https://github.com/SciSharp/LLamaSharp/blob/3d7bf4287c120f0c2f207ce58f997b4ee6411e97/LLama/Native/NativeApi.Load.cs#L321-L331

## Possible Solution: Interact with cuda before "succeeding"?

Perhaps `TryLoad()` shouldn't blindly return the pointer, but rather actually load the library and interact with it (e.g., getting `ContextSize` without crashing) before indicating that the loading was successful. I tried to figure out how to do this without loading a heavy model (maybe there's a dummy model or something used for testing?) but haven't been able to figure that out yet. I'll keep poking at this issue, but I welcome feedback in case anyone has suggestions!

**Comment by swharden** [comment]
Perhaps related, I wonder if this should throw if the returned value is 0

https://github.com/SciSharp/LLamaSharp/blob/3d7bf4287c120f0c2f207ce58f997b4ee6411e97/LLama/Native/NativeApi.cs#L20-L27

**Comment by martindevans** [comment]
What is [this method](https://github.com/SciSharp/LLamaSharp/blob/3d7bf4287c120f0c2f207ce58f997b4ee6411e97/LLama/Native/NativeApi.Load.cs#L62) returning for your system?

**Comment by swharden** [comment]
I have a little more info.... my environment variables are signaling to use cuda 12

![image](https://github.com/SciSharp/LLamaSharp/assets/4165489/e47bd446-a497-491f-8943-d8a7369d5444)

https://github.com/SciSharp/LLamaSharp/blob/3d7bf4287c120f0c2f207ce58f997b4ee6411e97/LLama/Native/NativeApi.Load.cs#L66-L74

> What is [this method](https://github.com/SciSharp/LLamaSharp/blob/3d7bf4287c120f0c2f207ce58f997b4ee6411e97/LLama/Native/NativeApi.Load.cs#L62) returning for your system?

ha! we converged on the same thing at the same time

**Comment by swharden** [comment]
Success! 🚀 

Uninstalling the NCIDIA CUDA toolkit automatically deleted the `CUDA_PATH` environment variable and the example runner works as expected.

![image](https://github.com/SciSharp/LLamaSharp/assets/4165489/fb2e173f-4f6a-45b3-a64a-d515153c0e75)

Thanks so much for your input along the way!

I wonder if there's something we can do to detect this issue and show a more helpful error message to the user: when the cuda DLL is detected but it can't be used because the available hardware doesn't support it...
