### ISSUE TITLE
LlamaSharp.Backend.MacMetal is broken

### ISSUE THREAD

**Issue by vshapenko** [SciSharp/LLamaSharp#527]
Hi! trying to use LlamaSharp.Backend.MacMetal  on latest LlamaSharp version and get following error: 

/usr/local/share/dotnet/dotnet /Users/codechanger/RiderProjects/LLama.Bot/LLama/bin/Debug/net7.0/LLama.dll
Unhandled exception. System.TypeInitializationException: The type initializer for 'LLama.Native.NativeApi' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'llama_max_devices' in shared library 'llama'.
   at LLama.Native.NativeApi.llama_max_devices()
   at LLama.Native.NativeApi.llama_empty_call()
   at LLama.Native.NativeApi..cctor()
   --- End of inner exception stack trace ---
   at LLama.Native.NativeApi.llama_max_devices()
   at LLama.Abstractions.TensorSplitsCollection..ctor()
   at LLama.Common.ModelParams..ctor(String modelPath)
   at LLamaSharp.KernelMemory.BuilderExtensions.WithLLamaSharpDefaults(IKernelMemoryBuilder builder, LLamaSharpConfig config)
   at <StartupCode$LLama>.$Program.main@() in /Users/codechanger/RiderProjects/LLama.Bot/LLama/Program.fs:line 28

On Backend.CPU same code works. 

Where should i look to fix this issue?

**Comment by vshapenko** [comment]
below is code i use for test
```fsharp
  open System
  open LLama.Common
  open LLamaSharp.KernelMemory
  open Microsoft.FSharp.Core
  open Microsoft.KernelMemory
  
  open Microsoft.KernelMemory.Configuration
  open FSharp.Control
  
  
  let config = LLamaSharpConfig("/Users/codechanger/llama/mistral-7b-instruct-v0.2.Q5_K_S.gguf")
  config.DefaultInferenceParams<-InferenceParams()
  config.DefaultInferenceParams.AntiPrompts<- [| "[/INST]" |]
  let prompt txt = $"[INST] {txt} [/INST]"
  let searchClientConfig = SearchClientConfig( 
                  MaxMatchesCount = 1,
                  AnswerTokens = 100)
  let memory =
        KernelMemoryBuilder()
          .WithLLamaSharpDefaults(config)
          .WithSearchClientConfig(searchClientConfig)
          .With(new TextPartitioningOptions(
                          MaxTokensPerParagraph = 300,
                          MaxTokensPerLine = 100,
                          OverlappingTokens = 30))
          .Build()
  
  task{
    let! _ = memory.ImportDocumentAsync("/Users/codechanger/Downloads/2306.10763.pdf", steps = Constants.PipelineOnlySummary)
    let question = prompt "Summarize this paper"
  
    printfn "\n\nQuestion: %s" question
  
    let! answer = memory.AskAsync(question)
  
    printfn "\nAnswer: %s" answer.Result
  
    printfn "\n\n  Sources:\n"
  
    for x in answer.RelevantSources do
      printfn "  - %s  - %s [%O]" x.SourceName x.Link (x.Partitions|> Seq.head|> (fun x-> x.Text))
  } |> ignore
  
  Console.ReadLine() |> ignore
```

**Comment by martindevans** [comment]
That's odd, `llama_max_devices` does exist ([here](https://github.com/ggerganov/llama.cpp/blob/master/llama.h#L346)). My best guess is there's something wrong with the MacMetal build, but I don't know enough about mac to say what it could be.

@SignalRT any ideas?

**Comment by SignalRT** [comment]
@martindevans It's working for me on the master. @vshapenko  What version are you using?. This weekend I will work on publish what I done with Llava and I will happy to review this issue.

**Comment by SignalRT** [comment]
I can find any error on Mac even with the latest binaries compiled 2 days ago.

**Comment by SignalRT** [comment]
@vshapenko Any news on this issue?

**Comment by SignalRT** [comment]
I will close this issue. I can´t reproduce.

**Comment by Arlodotexe** [comment]
I was able to reproduce the error while trying to manually load the DLLs, files copied into `I:\llama\active\`
```cs
NativeLibraryConfig.LLama
            .WithLibrary(@"I:\llama\active\ggml-cuda.dll")
            .WithCuda(true)
            .WithVulkan(false)
            .WithAutoFallback(false)
```

```
+363ms MarkZero StartAsync  [Critical]  Got relative library path 'I:\llama\active\ggml-cuda.dll' from local with , trying to load it...

+364ms MarkZero StartAsync  [Critical]  Found full path file 'I:\llama\active\ggml-base.dll' for relative path 'I:\llama\active\ggml-base.dll'

+365ms MarkZero StartAsync  [Critical]  Successfully loaded 'I:\llama\active\ggml-base.dll'

+366ms MarkZero StartAsync  [Critical]  Successfully loaded dependency 'I:\llama\active\ggml-base.dll'

+366ms MarkZero StartAsync  [Critical]  Found full path file 'I:\llama\active\ggml.dll' for relative path 'I:\llama\active\ggml.dll'

+366ms MarkZero StartAsync  [Critical]  Successfully loaded 'I:\llama\active\ggml.dll'

+367ms MarkZero StartAsync  [Critical]  Successfully loaded dependency 'I:\llama\active\ggml.dll'

+367ms MarkZero StartAsync  [Critical]  Found full path file 'I:\llama\active\ggml-cuda.dll' for relative path 'I:\llama\active\ggml-cuda.dll'

+460ms MarkZero StartAsync  [Critical]  Successfully loaded 'I:\llama\active\ggml-cuda.dll'

Unhandled exception: System.TypeInitializationException: The type initializer for 'LLama.Native.NativeApi' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'llama_max_devices' in DLL 'llama'.
   at LLama.Native.NativeApi.llama_max_devices()
   at LLama.Native.NativeApi.llama_empty_call()
   at LLama.Native.NativeApi..cctor()
   --- End of inner exception stack trace ---
   at LLama.Native.NativeApi.llama_max_devices()
   at LLama.Abstractions.TensorSplitsCollection..ctor()
   at LLama.Common.ModelParams..ctor(String modelPath)
```

Running on Windows (not Mac) with the latest llama.cpp DLLs.
