### ISSUE TITLE
Error with .SaveState()

### ISSUE THREAD

**Issue by mphacker** [SciSharp/LLamaSharp#85]
When calling SaveState on the executor I am getting the folliwing error:

"System.ArgumentException: '.NET number values such as positive and negative infinity cannot be written as valid JSON. To make it work when using 'JsonSerializer', consider specifying 'JsonNumberHandling.AllowNamedFloatingPointLiterals' (see https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonnumberhandling).'"

This is with 0.4.2-preview.

**Comment by martindevans** [comment]
Do you have a stacktrace from the error, to help track down exactly where it's coming from?

**Comment by mphacker** [comment]
System.ArgumentException
  HResult=0x80070057
  Message=.NET number values such as positive and negative infinity cannot be written as valid JSON. To make it work when using 'JsonSerializer', consider specifying 'JsonNumberHandling.AllowNamedFloatingPointLiterals' (see https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonnumberhandling).
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowArgumentException_ValueNotSupported()
   at System.Text.Json.Utf8JsonWriter.WriteNumberValue(Single value)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteStream[TValue](Stream utf8Json, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options)
   at LLama.InteractiveExecutor.SaveState(String filename)
   at ArchobotLLMServer.LLMServerAzureHybrid.<SetupLLMService>d__31.MoveNext() in C:\Users\Owner\source\repos\mphacker\Archobotcore\ArchobotLLMServer\LLMServerHybrid.cs:line 93

**Comment by mphacker** [comment]
I should mention that I am saving state right after creating a new executor so I have a "clean state" that I can reload later.

**Comment by martindevans** [comment]
I tracked down the issue to the `mirostat_mu` value. It's initially a `NaN` value to indicate a "not initialised yet" state and it gets set to a valid value the first time the model is evaluated. JSON serialization doesn't like NaN, so you get the error above.

Could you try out #88 to see if it fixes the issue for you? I've changed it to use a nullable float instead of a `NaN` value.

**Comment by martindevans** [comment]
I've merged #88, so this should be fixed in the master branch now. If you can confirm it works for you I'll close the issue

**Comment by mphacker** [comment]
Seems to work fine now.  Thanks!

**Comment by mphacker** [comment]
Works great!  Thanks
